### ISSUE TITLE
Can't migrate from Docker Compose setup to Portainer

### ISSUE THREAD

**Issue by valentin-gosselin** [azixus/ARK_Ascended_Docker#39]
Hello,

I've been successfully running an ARK server using the azixus/ark-ascended-docker image with Docker Compose for several months. However, for simplicity, I've been trying to migrate my setup to Portainer.

I have adapted my `docker-compose.yml` for use in Portainer as follows:

```
version: '3'

services:
  asa_server:
    tty: true
    restart: unless-stopped
    image: azixus/ark-ascended-docker
    volumes:
      - ${ARK_DATA_VOLUME}:/opt/arkserver
      - ${ARK_BACKUP_VOLUME}:/var/backups/asa-server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - default
    stop_grace_period: 45s
    deploy:
      resources:
        limits:
          memory: 12g
    memswap_limit: 12g

volumes:
    steam_data:
```

In this process, I've encountered a similar issue to the one reported in issue #23, where the logs show the following error:

`mkdir: cannot create directory '': No such file or directory`

I've followed the suggestions regarding permissions without success. I have not made any changes to the original .env file except for server-specific information like session name, password, and startup rules. Paths for STEAM_COMPAT_DATA_PATH and STEAM_COMPAT_CLIENT_INSTALL_PATH have not been altered.

Is there anything else I should consider in this migration process that could be causing this error? Any advice or suggestions would be greatly appreciated.

Thank you for your assistance.

**Comment by valentin-gosselin** [comment]
After further investigation and with some helpful pointers, I realized that the error was due to a misunderstanding on my part regarding the environment variable setup in Portainer. I initially placed the environment variables only in the "Environment Variables" section without properly defining them in the main environment section of my docker-compose configuration.

Once I adjusted my docker-compose.yml file to include the environment variables directly within the service definition and ensured that all variables were correctly defined and passed to the container, the error was resolved.

Here's the adjusted snippet of my docker-compose.yml:

```
version: '3'

services:
  asa_server:
    container_name: asa_server
    tty: true
    restart: unless-stopped
    image: azixus/ark-ascended-docker
    volumes:
      - ${ARK_DATA_VOLUME}:/opt/arkserver
      - ${ARK_BACKUP_VOLUME}:/var/backups/asa-server
    ports:
      - "7791:7791/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - ASA_APPID=${ASA_APPID}
      - SERVER_MAP=${SERVER_MAP}
      - SESSION_NAME=${SESSION_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - SERVER_SHUTDOWN_TIMEOUT=${SERVER_SHUTDOWN_TIMEOUT}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ARK_ADMIN_PASSWORD=${ARK_ADMIN_PASSWORD}
      - RCON_PORT=${RCON_PORT}
      - DISABLE_BATTLEYE=${DISABLE_BATTLEYE}
      - MODS=${MODS}
      - ARK_EXTRA_OPTS=${ARK_EXTRA_OPTS}
      - ARK_EXTRA_DASH_OPTS=${ARK_EXTRA_DASH_OPTS}
      - TINI_VERSION=${TINI_VERSION}
      - LOG_FILE=${LOG_FILE}
      - PID_FILE=${PID_FILE}
      - STEAM_COMPAT_CLIENT_INSTALL_PATH=${STEAM_COMPAT_CLIENT_INSTALL_PATH}
      - STEAM_COMPAT_DATA_PATH=${STEAM_COMPAT_DATA_PATH}
    networks:
      - default
    stop_grace_period: 45s
    deploy:
      resources:
        limits:
          memory: 12g
    memswap_limit: 12g


volumes:
  steam_data:
```

I hope this clarification helps others who might face similar issues.
